baseURL = "http://chrom.cn/"
languageCode = "zh-CN"
title = "Chao's Room"
theme = "smol"
staticDir = ["static"]

# Parameters
[params]
    subtitle = "芝兰生于幽谷，不以无人而不芳。"
    dateFmt = "02/01/2006 15:04"

# Taxonomies
[taxonomies]
      tag = "tags"
      category = "categories"
      archive = "archives"

# Header
[menu]
      [[menu.main]]
            identifier = "posts"
            name = "Posts"
            url = "/posts/"
            weight = 1

      [[menu.main]]
            identifier = "categories"
            name = "Categories"
            url = "/categories/"
            weight = 2

      [[menu.main]]
            identifier = "tags"
            name = "Tags"
            url = "/tags/"
            weight = 3

      [[menu.main]]
            identifier = "about"
            name = "About"
            url = "/about/"
            weight = 4

# Footer
      [[menu.footer]]
            name = "Github"
            url = "https://github.com/zhilancc"
            weight = 1

      [[menu.footer]]
            name = "Twitter"
            url = "https://twitter.com/zhilan_cc"
            weight = 2

      [[menu.footer]]
            name = "Linkedin"
            url = "https://www.linkedin.com/"
            weight = 3
